language: java
jdk:
 - oraclejdk8
cache:
  directories:
   - $HOME/.m2

install:
- mvn -f app-game-catolog/pom.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn -f app-game-catolog/pom.xml test

script:
- mvn -f app-game-catolog/pom.xml cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
